test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,6 +5,19 @@
 # yarn tsc --build
 # yarn build
 # yarn lint
-yarn workspace server test
-yarn workspace client test
+yarn workspace server test || {
+        echo "husky > pre-commit|push hook failed (add --no-verify to bypass)"
+        echo "***********************************************************************************************************"
+        echo "**** Nice try, but you can't commit this. Happy bug hunting and error fixing, good luck!"
+        echo "***********************************************************************************************************"
+        exit 1
+      }
+yarn workspace client test || {
+        echo
+        echo "husky > pre-commit|push hook failed (add --no-verify to bypass)"
+        echo "***********************************************************************************************************"
+        echo "**** Nice try, but you can't commit this. Happy bug hunting and error fixing, good luck!"
+        echo "***********************************************************************************************************"
+        exit 1
+      }
 
